### ISSUE TITLE
Summary plot empty

### ISSUE THREAD

**Issue by shahn** [japaric/criterion.rs#105] opened 2017-12-26 18:14 UTC
This function produces empty summary plots:
```
fn tree_insert(c: &mut Criterion) {
    let mut arr = [0; 3];
    for i in 0..3 {
        arr[i] = i;
    }
    c.bench_function_over_inputs("insert elem",
                                 |b, &&size| {
        b.iter_with_setup(move || {
            let mut mt = MerkleTree::<sha2::Sha256>::new();
            for i in 1..size {
                mt.insert(<sha2::Sha256 as digest::Digest>::hash_elem(&A(i)));
            }
            mt
        }, |mut tree| tree.insert(<sha2::Sha256 as digest::Digest>::hash_elem(&A(size))))
    },
    arr.iter());
}
```
when run on Linux (gnuplot 5.0 patchlevel 5).
![summary](https://user-images.githubusercontent.com/128636/34362117-0172c27a-ea71-11e7-8218-65d682eca76a.png)

**Comment by bheisler** [comment] 2017-12-28 00:38
I think this is a duplicate of #104. If not, please reopen this issue and provide the relevant gnuplot scripts and debug output (see [Debug Output](https://japaric.github.io/criterion.rs/book/criterion_rs.html#debug-output) for how to enable that).

**Closed by bheisler** 2017-12-28 00:38 UTC

**Comment by shahn** [comment] 2017-12-28 01:03
Yes it is, thank you 👍
