### ISSUE TITLE
add capability of determining scaling of a function

### ISSUE THREAD

**Issue by droundy** [japaric/criterion.rs#187] opened 2018-08-07 14:15 UTC
I love that we can specify a set of inputs to run criterion on, but it would be lovely to be able to give a set of inputs and then have criterion perform a regression to tell us how our code scales, i.e. what is the O(0) term, the O(N) term, etc, with reasonable confidence.  Even better, tell us which of these are probably non-zero with a P value.

Currently I do this by eye through examining the graphs, but that isn't the most accurate approach.

**Comment by bheisler** [comment] 2018-08-09 12:56
Hey, thanks for the suggestion!

That would be neat, but it seems like it would be a relatively niche feature in relation to how difficult it would be to implement.

**Comment by gnzlbg** [comment] 2018-09-20 11:04
This might be a duplicate of #111 .

**Comment by droundy** [comment] 2018-09-20 17:30
@gnzlbg Yes it does look like it strongly overlaps with #111.

**Comment by bheisler** [comment] 2018-10-08 14:32
Closing as a duplicate.

**Closed by bheisler** 2018-10-08 14:32 UTC
