### ISSUE TITLE
Throughput in plot if configured

### ISSUE THREAD

**Issue by RCasatta** [japaric/criterion.rs#177] opened 2018-07-18 09:58 UTC
I am testing a function which is more efficient per element the more elements there are.
In this case the throughput is more interesting than the time.

In the case the throughput is configured isn't better to show it in the graphs? (especially it would be great in the violin plot)

**Comment by bheisler** [comment] 2018-07-19 02:03
Hey, thanks for trying Criterion.rs! Thanks for the suggestion, but this is a duplicate of #149.

**Closed by bheisler** 2018-07-19 02:03 UTC

**Comment by qsantos** [comment] 2023-11-16 09:58
It looks like #149 was moved to https://github.com/bheisler/cargo-criterion/issues/9.
