### ISSUE TITLE
Change sometimes printed as "%NaN +%inf %NaN"

### ISSUE THREAD

**Issue by Restioson** [japaric/criterion.rs#140] opened 2018-04-11 16:59 UTC
Hi! I just tried out criterion, and the first time that I ran my benchmark *successfully* (without panics) it outputted this:

```
Benchmarking rb_tree_vecs allocate_exact: Analyzing
rb_tree_vecs allocate_exact
                        time:   [8.0364 us 9.6646 us 11.727 us]
                        change: [   NaN%   +inf%    NaN%] (p = 0.00 < 0.05)
                        Change within noise threshold.
Found 5 outliers among 100 measurements (5.00%)
  3 (3.00%) high mild
  2 (2.00%) high severe
```

The second time I ran it (with small modifications) it outputted an expected

```
Benchmarking rb_tree_vecs allocate_exact: Analyzing
rb_tree_vecs allocate_exact
                        time:   [8.1839 us 8.4555 us 8.7618 us]
                        change: [-18.556% -6.5726% +5.6153%] (p = 0.36 > 0.05)
                        No change in performance detected.
Found 8 outliers among 100 measurements (8.00%)
  2 (2.00%) low mild
  4 (4.00%) high mild
  2 (2.00%) high severe
```

Perhaps something goes wrong when a panic is encountered during a benchmark? Or maybe it's because it was the first benchmark that finished successfully. Anyway, it probably shouldn't at least be printing `NaN`, and maybe not `inf`.

**Comment by bheisler** [comment] 2018-04-14 19:51
Hey, thanks for trying Criterion.rs!

I think it's likely that this was simply a corrupted measurement file, probably caused by https://github.com/japaric/criterion.rs/issues/139. I'd ask you to provide the damaged file, but it will have been deleted by now.

I'm going to close this as a duplicate for now, but if you think that's not correct or if you can find a way to cause it to happen again, please reopen.

**Closed by bheisler** 2018-04-14 19:51 UTC

**Comment by Restioson** [comment] 2018-04-14 20:52
Cool, I'll try out the commit later when I can.
